### ISSUE TITLE
No module named 'tinyms'

### ISSUE THREAD

**Issue by Frozen-hc** [tinyms-ai/tinyms#100]
## Environment

- **TinyMS version (source or binary)0.2.1:
- **Framework and version (e.g., MindSpore v1.1.1)MindSpore v1.2.0:
- **Python version (e.g., Python 3.7.5)3.8.2:
- **Hardware backend (e.g., CPU)CPU:
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)windows 11 .22000.160:

When I input “import tinyms”，it output “No module named 'tinyms'”

**Comment by hellowaywewe** [comment]
It means the installation of TinyMS is unsuccessful,  currently, TinyMS supports ubuntu 18.04, not ubuntu  16.04. I think you can see if there is an error message when you install TinyMS.

**Comment by hellowaywewe** [comment]
If you don't have any problems with this issue,  I will close it.

**Comment by hellowaywewe** [comment]
If you don't have any problems with this issue,  I will close it.
