### ISSUE TITLE
Too old for opencv in requirements.txt

### ISSUE THREAD

**Issue by ouening** [tinyms-ai/tinyms#124]
When I try to install tinyms in Windows using command: `pip install tinyms==0.3.0`, some error occured:
```
ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.2.30 (from tinyms) (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.14.51, 3.4.14.53, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.2.52, 4.5.2.54, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62)
ERROR: No matching distribution found for opencv-python==4.1.2.30
```
Maybe it is too old to use opencv-python4.1.2.30

**Comment by hellowaywewe** [comment]
@ouening Thanks for your issue, it will be improved next version.

**Comment by hellowaywewe** [comment]
@ouening This problem has been solved in the new version, welcome to try. I will close this issue first, if there are other problems, you can create a new issue, thanks.
