### ISSUE TITLE
Definition servable.json must the path /etc/tinyms/serving be specified?

### ISSUE THREAD

**Issue by hu-qi** [tinyms-ai/tinyms#62]
请问`servable.json `必须存放在指定路径`/etc/tinyms/serving`下吗？
当我调用 `list_servables()` 时，发现它默认访问`/etc/tinyms/serving/servable.json`。
![image](https://user-images.githubusercontent.com/17986122/113289679-1a574f00-9323-11eb-96e9-ebaadb79f2ce.png)

**Comment by hu-qi** [comment]
看代码好像是[写死的](https://github.com/tinyms-ai/tinyms/blob/a684916eeb5aa2c04c0dc60fc18be256ec7027f6/tinyms/serving/servable/servable.py#L23:1)

```
servable_path = '/etc/tinyms/serving/servable.json'
```
能否支持自定义路径？

**Comment by leonwanghui** [comment]
@hu-qi Currently the servable_path is defined in hard-code, but it would be refactored in the next release, would like to pull a request?

**Comment by leonwanghui** [comment]
@hu-qi This issue has been addressed by PR #76 and #77, please download the latest version of TinyMS and have a try with it.
