### ISSUE TITLE
使用MindSpore高阶工具TinyMS支持的网络CycleGAN训练图像风格迁移模型

### ISSUE THREAD

**Issue by huxiaoman7** [tinyms-ai/tinyms#78]
## 任务

- 结合MindSpore高阶工具TinyMS支持的模型CycleGAN，运用真实场景数据做迁移学习，训练城市风格迁移模型

## 要求

- 需使用TinyMS搭建的CycleGAN网络
- 需使用自己的数据做迁移学习，可基于TinyMs提供的预训练模型进行训练，也可以自行训练
- 需有明确的应用场景和实际意义

## 资料
- CycleGAN教程：https://github.com/tinyms-ai/tinyms/blob/main/docs/zh_CN/source/tutorials/ipynb/TinyMS_CycleGAN_tutorial_zh.ipynb

**Comment by hellowaywewe** [comment]
活动已结束，关闭
