### ISSUE TITLE
使用MindSpore高阶工具TinyMS复现人脸检测模型FaceDetection，制作人脸检测仪器

### ISSUE THREAD

**Issue by huxiaoman7** [tinyms-ai/tinyms#79]
## 任务

- 使用MindSpore高阶工具TinyMS复现人脸检测模型FaceDetection，运用真实场景数据做迁移学习，并迁移到硬件上，制作人脸检仪器

## 要求

- 需使用TinyMS复现FaceDetecion
- 需自行收集数据做训练
- 需有明确的应用场景和实际意义

## 资料
- FaceDetection：https://gitee.com/mindspore/mindspore/tree/r1.2/model_zoo/research/cv/FaceDetection

**Comment by zjuter0126** [comment]
1. 请问对于提交的模型是否有性能上的要求
2. 模型的硬件是否有要求

**Comment by hellowaywewe** [comment]
活动已结束，关闭
