### ISSUE TITLE
使用MindSpore高阶工具TinyMS复现海洋模型GOMO，有实际应用意义

### ISSUE THREAD

**Issue by huxiaoman7** [tinyms-ai/tinyms#80]
## 任务

- 使用MindSpore高阶工具TinyMS复现GOMO模型，有实际应用意义

## 要求

- 需使用TinyMS复现GOMO
- 需有明确的应用场景和实际意义

## 资料
- GOMO 代码：https://gitee.com/mindspore/mindspore/tree/r1.2/model_zoo/research/hpc/ocean_model

**Comment by hellowaywewe** [comment]
活动已结束，关闭
